name: Integration test on schedule (minimal)
concurrency: ${{ github.workflow }}-${{ github.ref }}
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  start-integration-test-minimal:
    name: Start integration test (minimal)
    uses: ./.github/workflows/integration.yml
    secrets: inherit
    with:
      install_profile: minimal
      cluster_region: ams3
